# Further instructions at https://bot.krd.me/getting-the-bot#running-with-docker

FROM python:3.7
COPY . /bot
WORKDIR /bot
RUN pip3.7 install -r requirements.txt
CMD [ "python3.7", "./start.py", "--scheduled_refresh" ]
